# -*- coding: utf-8 -*-
"""class-120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PEry9sCFYkbQw_RpWzYukQdn8LNVFO9F
"""

from google.colab import files
a = files.upload()

import pandas as pd

df = pd.read_csv('class-120.csv')
print(df.head())

from sklearn.model_selection import train_test_split

X = df[["glucose","bloodpressure"]]
Y = df['diabetes']

X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.25, random_state=42)

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

model_1 = GaussianNB()
model_1.fit(X_train, Y_train)

y_pred = model_1.predict(X_test)

accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)

from sklearn.model_selection import train_test_split

X = df[["glucose","bloodpressure"]]
Y = df['diabetes']

X_train_1, X_test_1,Y_train_1,Y_test_1 = train_test_split(X,Y, test_size=0.25, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train_1 = sc.fit_transform(X_train_1)
X_test_1 = sc.fit_transform(X_test_1)

model_2 = LogisticRegression(random_state=0)
model_2.fit(X_train_1, Y_train_1)

y_pred = model_2.predict(X_test_1)

accuracy = accuracy_score(Y_test_1, y_pred)
print(accuracy)